version: "3.9"
services:
  db:    
    image: postgres:13.0-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env

  db_test:    
    image: postgres:13.0-alpine
    restart: unless-stopped
    ports:
      - "6000:5432"
    environment:
      POSTGRES_DB: ${DB_NAME_TEST}
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASS_TEST}
    env_file:
      - ./.env

  # backend:
  #   container_name: backend
  #   build:
  #     context: ../.
  #     dockerfile: Dockerfile
  #   expose:
  #     - 8000
  #   ports:
  #     - "8000:8000" 
  #   restart: always
  #   command: ["/catalog_of_articles_fastapi/docker/app.sh"]
  #   depends_on:
  #     - db
