"""First migration

Revision ID: ecb524339844
Revises: d5f7322a5b5f
Create Date: 2023-10-03 12:46:31.154496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb524339844'
down_revision: Union[str, None] = 'd5f7322a5b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_title', table_name='articles')
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=True)
    op.create_unique_constraint(None, 'articles', ['description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.create_index('ix_articles_title', 'articles', ['title'], unique=False)
    # ### end Alembic commands ###
